import Head from 'next/head';
import React from 'react';

import { BudgetList } from '../components/BudgetList/BudgetList';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style={{ padding: '0 80px' }}>
                <BudgetList />
            </div>
        </>
    );
}
